### PR TITLE
Add Travis CI config

### PR DESCRIPTION
**Pull request by w-miller**

### CODE REVIEW

**Comment by markgoddard** [comment]
Looks like TravisCI isn't liking the use of python3 (specified in tox.ini). It uses very old Ubuntu 14.04 images, and Ansible claims not to be

**Comment by w-miller** [comment]
Yeah, I just pushed a commit to remove the basepython overrides and see if that changed anything, but the virtualenv package install still doesn't seem to be working either. Did you mean to close this PR?

**Comment by markgoddard** [comment]
Sorry, think I clicked on close and comment by accident!

**Comment by w-miller** [comment]
I've done that before as well! Did you click that mid-comment as well, by any chance?

**Comment by markgoddard** [comment]
Yeah, I saw your new commits, so stopped typing :)

**Comment by w-miller** [comment]
Looks like it works okay with Python 2.7.

**Review by markgoddard — APPROVED** [review]

**Pull request merged**
